server:
  port: 7888
spring:
  datasource:
    url: jdbc:h2:~/community
    username: kycni
    password: 123456
    driver-class-name: org.h2.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true